inherit_gem:
  google-style: google-style.yml

Metrics/BlockLength:
  Exclude:
    - "test/**/test_*.rb"
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Naming/FileName:
  Exclude:
    - "examples/*/Gemfile"
    - ".toys/**/*.rb"
Style/IfUnlessModifier:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
