inherit_gem:
  google-style: google-style.yml

Lint/UnusedMethodArgument:
  Exclude:
    - "lib/cloud_events/format.rb"
Metrics/BlockLength:
  Exclude:
    - "test/**/test_*.rb"
Metrics/ClassLength:
  Max: 300
Metrics/ModuleLength:
  Max: 300
Naming/FileName:
  Exclude:
    - "examples/*/Gemfile"
    - ".toys/**/*.rb"
