name: "(continuous)"

on:
  push:
    branches:
      - master

jobs:
  tests:
    if: ${{ github.repository == 'cloudevents/sdk-ruby' }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ "2.4", "2.5", "2.6", "2.7", "jruby" ]
        include:
          - os: ubuntu-latest
            ruby: "2.7"
            tool: ci
          - os: macos-latest
            ruby: "2.7"
          - os: windows-latest
            ruby: "2.7"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        shell: bash
        run: "bundle install && gem install --no-document toys"
      - name: Run ${{ matrix.tool || 'test' }}
        shell: bash
        run: |
          toys "${{ matrix.tool || 'test' }}" < /dev/null
  post-push:
    needs: [tests]
    if: ${{ always() && github.repository == 'cloudevents/sdk-ruby' }}
    runs-on: ubuntu-latest
    env:
      ruby_version: "2.7"
    steps:
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Toys
        run: "gem install --no-document toys"
      - name: Handle release PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release perform --yes --verbose \
            "--ci-result=${{ needs.tests.result }}" \
            "--enable-releases=${{ secrets.ENABLE_RELEASES }}" \
            "--git-user-email=${{ secrets.GIT_USER_EMAIL }}" \
            "--git-user-name=${{ secrets.GIT_USER_NAME }}" \
            "--github-sha=${{ github.sha }}" \
            "--rubygems-api-key=${{ secrets.RUBYGEMS_API_KEY }}" \
            < /dev/null
